### ISSUE TITLE
Fix For Ip?

### ISSUE THREAD

**Issue by Glatrix** [e9x/e9x.github.io#2]
Any chance you could make the change IP manual?
I keep getting an error saying "Too many ip's, if you have any extensions please disable them."

Maybe make a button for Change IP and a button for use my IP

**Comment by e9x** [comment]
thats because too many people on your overcrowded network are krunkering

**Comment by Glatrix** [comment]
No, nobody else here is playing it. Its because the page keeps refreshing when the hack is on and
every time the page refreshes, the IP changes. If the hack picked 1 IP and stuck with it, it would be fine.
I understand what you mean though, but this error is not saying "Too Many Instances Of The Same Ip", Its saying
that I'm connecting with too many different IP's. I have found a temp fix... I'm using my own VPN.
Maybe implement a built-in vpn if possible? or make ip changing more manual.

**Comment by Glatrix** [comment]
I don't mean to be rude. I simply want to make sure nobody else has the same issue.

**Comment by e9x** [comment]
its because of too many ips connecting
